name: plugilo
description: "Plugilo App"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  # general
  equatable: ^2.0.7
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  # state management
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  # dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0
  # network
  dio: ^5.8.0+1
  curl_logger_dio_interceptor: ^1.0.0
  network_logger: ^1.0.4
  # firebase
  firebase_core: ^3.10.1
  firebase_analytics: ^11.4.1
  firebase_crashlytics: ^4.3.1
  firebase_messaging: ^15.2.1
  firebase_remote_config: ^5.3.1
  firebase_database: ^11.3.1
  # storage
  shared_preferences: ^2.5.1
  flutter_secure_storage: ^9.2.4
  # routing
  go_router: ^14.7.2
  # localization
  easy_localization: ^3.0.7+1
  # utils
  universal_io: ^2.2.2
  package_info_plus: ^8.2.0
  device_info_plus: ^11.2.2
  url_launcher: ^6.3.1
  flutter_dotenv: ^5.2.1
  validators: ^3.0.0
  # ui
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  flutter_styled_toast: ^2.2.1
  event_hub: ^0.2.1
  flutter_local_notifications: ^18.0.1
  share_plus: ^10.1.4
  flutter_screenutil: ^5.9.3
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_gen_runner: ^5.9.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.3
  freezed: ^2.5.8

flutter_gen:
  output: lib/generated/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/env/
    - assets/images/
    - assets/svg/
    - assets/translations/
