import 'dart:convert';

import 'package:equatable/equatable.dart';
import 'package:plugilo/core/utils/cast.dart';

class ApiResponseMeta extends Equatable {
  const ApiResponseMeta({
    this.code,
    this.message,
    this.errors,
  });
  final String? code;
  final String? message;
  final ApiResponseMetaErrors? errors;

  @override
  bool operator ==(Object other) => other is ApiResponseMeta && code == other.code && errors?.externalErrorCode == other.errors?.externalErrorCode;

  @override
  int get hashCode => Object.hash(code, errors?.errorCode);

  Map<String, dynamic> toJson() {
    return {
      'Code': code,
      'Message': message,
      'Errors': errors?.toJson(),
    };
  }

  String toJsonString() => json.encode(toJson());

  factory ApiResponseMeta.fromJson(Map<String, dynamic>? map) {
    final errors = ApiResponseMetaErrors.fromJson(map?['Errors']);
    return ApiResponseMeta(
      code: errors.externalErrorCode ?? safeCastString(map?['Code']),
      message: errors.externalErrorMessage ?? safeCastString(map?['Message']),
      errors: ApiResponseMetaErrors.fromJson(map?['Errors']),
    );
  }

  // account
  factory ApiResponseMeta.accountLocked() => ApiResponseMeta.fromCode('12009');
  factory ApiResponseMeta.accountExists() => ApiResponseMeta.fromCode('21032');
  factory ApiResponseMeta.expiredToken() => ApiResponseMeta.fromCode('51201');
  factory ApiResponseMeta.expiredSession() => ApiResponseMeta.fromCode('51202');
  factory ApiResponseMeta.overInvalidOtp() => ApiResponseMeta.fromCode('51306');
  factory ApiResponseMeta.overRequestOtp() => ApiResponseMeta.fromCode('51324');
  factory ApiResponseMeta.overInvalidPassword() => ApiResponseMeta.fromCode('14123');
  factory ApiResponseMeta.oldPasswordIsIncorrect() => ApiResponseMeta.fromCode('14121');
  factory ApiResponseMeta.contractCodeIsIncorrect() => ApiResponseMeta.fromCode('41014');
  factory ApiResponseMeta.theBillHasBeenPaid() => ApiResponseMeta.fromCode('41002');
  factory ApiResponseMeta.transactionFail() => ApiResponseMeta.fromCode('51325');

  // full error codes
  factory ApiResponseMeta.fromCode(String code) {
    final errors = ApiResponseMetaErrors.fromCode(code);
    return ApiResponseMeta(code: code, message: errors.message, errors: errors);
  }

  @override
  List<Object?> get props => [code, message, errors];
}

class ApiResponseMetaErrors {
  ApiResponseMetaErrors({
    this.externalErrorCode,
    this.externalErrorMessage,
    this.errorCode,
    this.message,
    this.path,
    this.url,
    this.sourceError,
  });

  String? externalErrorCode;
  String? externalErrorMessage;
  String? errorCode;
  String? message;
  String? path;
  String? url;
  String? sourceError;

  Map<String, dynamic> toJson() {
    return {
      'ExternalErrorCode': externalErrorCode,
      'ExternalErrorMessage': externalErrorMessage,
      'ErrorCode': errorCode,
      'Message': message,
      'Path': path,
      'Url': url,
      'SourceError': sourceError,
    };
  }

  String toJsonString() => json.encode(toJson());

  factory ApiResponseMetaErrors.fromJson(Map<String, dynamic>? map) {
    return ApiResponseMetaErrors(
      externalErrorCode: safeCastString(map?['ExternalErrorCode']),
      externalErrorMessage: safeCastString(map?['ExternalErrorMessage']),
      errorCode: safeCastString(map?['ErrorCode']),
      message: safeCastString(map?['Message']),
      path: safeCastString(map?['Path']),
      url: safeCastString(map?['Url']),
      sourceError: safeCastString(map?['SourceError']),
    );
  }

  factory ApiResponseMetaErrors.fromCode(String code) {
    return ApiResponseMetaErrors(
      externalErrorCode: code,
      externalErrorMessage: errorCodes[code] ?? '',
      errorCode: code,
      message: errorCodes[code] ?? '',
      path: '',
      url: '',
      sourceError: '',
    );
  }

  static Map<String, String> errorCodes = {
    '11001': 'Thông tin/loại thẻ không hợp lệ/không tồn tại hoặc không được hỗ trợ',
    '11002': 'Tên chủ thẻ không hợp lệ',
    '11003': 'Ngày phát hành/hết hạn của thẻ không hợp lệ',
    '11004': 'Mã bảo mật thẻ (CVV, CSC) không hợp lệ',
    '11005': 'Thẻ chưa được liên kết',
    '11006': 'Thẻ đã được liên kết',
    '11007': 'Thẻ chưa đăng ký 3DS',
    '11008': 'Thẻ chưa đăng ký dịch vụ thanh toán trực tuyến',
    '11009': 'Thẻ đã bị khóa',
    '11010': 'Thẻ không đủ điều kiện, không được phép thanh toán hoặc đang ở trạng thái không giao dịch được',
    '11011': 'Thẻ hết hạn sử dụng',
    '11012': 'Thẻ không hoạt động',
    '11013': 'Thẻ bị ngân hàng từ chối, hoặc do thẻ không phải phát hành tại Việt Nam',
    '11014': 'Loại thẻ không được hỗ trợ thực hiện giao dịch',
    '11015': 'Loại thẻ không hỗ trợ thanh toán trực tuyến',
    '11016': 'Không xác định được số dư trong thẻ',
    '11017': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '11018': 'Thẻ không tồn tại',
    '11019': 'Trạng thái của thẻ không hợp lệ',
    '11020': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '11021': 'Thẻ đã bị đóng',
    '11022': 'Mã PIN thẻ không hợp lệ',
    '11023': 'Mã PIN thẻ không chính xác',
    '11024': 'Thẻ đã đăng ký dịch vụ thanh toán trực tuyến',
    '11025': 'Thẻ này hiện không thể liên kết do vừa thực hiện huỷ liên kết trước đó, vui lòng thử liên kết lại sau.',
    '11026': 'Thẻ hiện không thể liên kết do đã từng được liên kết với một ví ĐVTGTT khác, vui lòng thử lại sau {x} ngày.',
    '11027': 'Thẻ không hỗ trợ chuyển đổi trả góp',
    '12001': 'Thông tin/loại tài khoản không hợp lệ/không tồn tại hoặc không được hỗ trợ',
    '12002': 'Tài khoản thụ hưởng không hợp lệ',
    '12003': 'Thông tin tài khoản thụ hưởng không chính xác',
    '12004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12005': 'Tài khoản chưa được liên kết',
    '12006': 'Tài khoản đã được liên kết',
    '12008': 'Tài khoản chưa đăng ký dịch vụ thanh toán trực tuyến',
    '12009': 'Tài khoản đã bị khóa',
    '12010': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12011': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12012': 'Tài khoản không hoạt động',
    '12014': 'Loại tài khoản không được hỗ trợ thực hiện giao dịch',
    '12016': 'Không xác định được số dư trong tài khoản',
    '12017': 'Không hỗ trợ tra cứu số dư tài khoản',
    '12018': 'Tài khoản không tồn tại',
    '12019': 'Trạng thái tài khoản không hợp lệ',
    '12020': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12021': 'Tài khoản đã bị đóng',
    '12022': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12023': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12024': 'Tài khoản đã đăng ký dịch vụ thanh toán trực tuyến',
    '12025': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12026': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12027': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12028': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12029': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12030': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12031': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12032': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12033': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12034': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12035': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12036': 'Tài khoản này hiện không thể liên kết do vừa thực hiện huỷ liên kết trước đó, vui lòng thử liên kết lại sau x phút nữa.',
    '12037': 'Tài khoản không đủ điều kiện, không được phép thanh toán hoặc đang ở trạng thái không giao dịch được',
    '12038': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12039': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '12040': 'Tên tài khoản không khớp',
    '12041': 'Tài khoản hiện đang được đăng nhập ở thiết bị khác, vui lòng kiểm tra lại.',
    '12100': 'Tài khoản kết nối đối tác không tồn tại hoặc chưa đăng ký',
    '12101': 'Tài khoản kết nối đối tác bị khóa hoặc không còn hoạt động',
    '13001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13006': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13007': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13009': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13010': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '13011': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14101': 'Ví đang bị khóa',
    '14102': 'Ví chưa được kích hoạt',
    '14103': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14104': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14105': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14106': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14107': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14108': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14109': 'User hoặc mật khẩu đăng nhập không đúng',
    '14110': 'Thông tin người dùng ví không đúng',
    '14111': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14112': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '14113': 'Ví đã liên kết đúng với user BIDV online xác thực',
    '14114': 'Ví đã được liên kết với tải khoản',
    '14115': 'Ví chưa được liên kết với tài khoản',
    '14116': 'Tài khoản ví không đủ số dư',
    '14117': 'Trạng thái liên kết không hợp lệ',
    '14118': '',
    '14119': '',
    '14120': '',
    '14121': 'Mật khẩu cũ không chính xác',
    '14122': 'Mật khẩu mới trùng với mật khẩu đã dùng trước đó',
    '14123': 'Bạn đã nhập sai mật khẩu quá 05 lần. Vui lòng thử lại sau 1 giờ nữa!',
    '15001': 'Token đã tồn tại',
    '15002': 'Token không tồn tại',
    '15003': 'Token đã hết hạn sử dụng',
    '15004': 'Token đã bị huỷ bỏ/thu hồi',
    '15005': 'Token chưa được kích hoạt',
    '15006': 'Token đang bị khoá tạm thời',
    '15007': 'Token đang bị hạn chế sử dụng tạm thời',
    '15008': 'Token không hợp lệ',
    '16001': 'Mã QR Code không tồn tại',
    '16002': 'Mã QR Code đã tồn tại',
    '16003': 'Mã QR Code không hợp lệ',
    '16004': 'Mã QR Code đã hết hạn',
    '16005': 'Dữ liệu QR Code đã bị thay đổi',
    '16006': 'Dữ liệu QR Code bị trống',
    '16007': 'Mã QR đã được thanh toán trước đó',
    '16008': 'Thanh toán nhiều QRCode không cùng merchant',
    '16009': 'Thanh toán nhiều QRCode không cùng terminal',
    '17001': '',
    '17002': '',
    '17003': '',
    '17004': '',
    '17005': '',
    '17006': '',
    '20001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '20002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '20003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '20004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '20005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '20006': '',
    '21001': 'Thông tin khách hàng không hợp lệ',
    '21002': 'Thông tin định danh cá nhân (CMND/CCCD/Passport/..) không hợp lệ',
    '21003': 'Thông tin định danh cá nhân (CMND/CCCD/Passport/..) không tồn tại',
    '21004': 'Thông tin định danh cá nhân (CMND/CCCD/Passport/..) đã tồn tại trong hệ thống',
    '21005': 'Thông tin cá nhân (CMT/Hộ chiếu, SĐT) không trùng khớp với thông tin khách hàng đăng ký sử dụng dịch vụ tại Ngân hàng',
    '21011': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '21012': 'Người dùng Non-KYCed',
    '21013': 'Trạng thái KYC không xác định',
    '21014': 'Xác thực KYC thất bại',
    '21015': 'Người dùng đã xác thực và liên kết tài khoản/thẻ với ngân hàng',
    '21016': 'Người dùng đã xác thực nhưng chưa liên kết tài khoản/thẻ với ngân hàng',
    '21020': 'Số điện thoại không tồn tại',
    '21021': 'Số điện thoại không hợp lệ hoặc không được hỗ trợ',
    '21022': 'Số điện thoại khách hàng đã bị khóa',
    '21023': 'Số điện thoại chưa được kích hoạt',
    '21024': 'Số điện thoại BUNO không trùng số điện thoại BIDV Online',
    '21025': 'Số điện thoại chưa được đăng ký nhận OTP tại Ngân hàng cho giao dịch thanh toán trực tuyến.',
    '21026': 'Số điện thoại đang thực hiện giao dịch chưa được đăng ký tại ngân hàng',
    '21030': 'Người dùng không đủ điều kiện để thực hiện tính năng này',
    '21031': 'Khách hàng nằm trong danh sách bị từ chối giao dịch.',
    '21032': 'Số điện thoại đã tồn tại',
    '21033': 'Người nhận đã KYCed',
    '21034': 'Người nhận Non-KYCed',
    '21035': 'Trạng thái KYC người nhận không xác định',
    '21036': 'Người nhận đã xác thực và liên kết tài khoản/thẻ với ngân hàng',
    '21037': 'Người nhận đã xác thực nhưng chưa liên kết tài khoản/thẻ với ngân hàng',
    '21038': 'Người dùng không tồn tại trong hệ thống',
    '21039': 'Người nhận không tồn tại trong hệ thống',
    '23001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23006': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23007': 'Sản phẩm của ngân hàng không hỗ trợ/không cho phép thực hiện tính năng này',
    '23008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23009': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23010': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '23011': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '24001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '24002': 'Nhà cung cấp không tồn tại',
    '24003': 'Nhà cung cấp đang tạm dừng hoạt động',
    '24004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '24005': 'Không hỗ trợ thanh toán với nhà cung cấp này',
    '25001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '25002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '25003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '25004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31006': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31007': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31009': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31010': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '31011': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32001': 'Giá trị giao dịch vượt quá hạn mức giao dịch trên ngày',
    '32002': 'Giá trị giao dịch vượt quá hạn mức giao dịch trên tháng',
    '32003': 'Giá trị giao dịch vượt quá giới hạn tối đa do cổng thanh toán đặt',
    '32004': 'Giá trị giao dịch nhỏ hơn số tiền tối thiểu do cổng thanh toán đặt',
    '32005': 'Giá trị giao dịch vượt qúa hạn mức tối đa quy định cho một giao dịch',
    '32006': 'Giá trị giao dịch nhỏ hơn hạn mức tối thiểu quy định cho một giao dịch',
    '32007': 'Giá trị giao dịch nằm ngoài phạm vi giới hạn',
    '32008': 'Giá trị giao dịch vượt quá hạn mức tín dụng cho phép.',
    '32009': 'Giao dịch vượt quá hạn mức tối đa Bypass OTP trong ngày cho một khách hàng',
    '32010': 'Giao dịch vượt quá hạn mức tối đa Bypass OTP trong ngày cho một dịch vụ',
    '32011': 'Giá trị giao dịch vượt qúa hạn mức tối đa  quy định cho một giao dịch với nguồn tiền này',
    '32012': 'Giá trị giao dịch vượt quá hạn mức giao dịch trên ngày với nguồn tiền này',
    '32013': 'Giá trị giao dịch vượt quá hạn mức giao dịch trên tháng với nguồn tiền này',
    '32014': 'Giá trị giao dịch vượt quá hạn mức giao dịch trên ngày với hợp đồng/mã khách hàng này',
    '32015': 'Giá trị giao dịch vượt quá hạn mức giao dịch trên tháng với hợp đồng/mã khách hàng này',
    '32016': 'Gía trị giao dịch vượt hạn mức thanh toán cho phép, yêu cầu xác thực OTP',
    '32017': 'Giá trị giao dịch thấp hơn giá trị hóa đơn cần thanh toán',
    '32018': 'Giá trị giao dịch cao hơn giá trị hóa đơn cần thanh toán',
    '32019': 'Tổng số lần giao dịch vượt quá số lần quy định trong ngày',
    '32020': 'Tổng số lần giao dịch vượt quá số lần quy định trong tháng',
    '32021': 'Tổng số lần giao dịch vượt quá số lần quy định trong ngày đối với hợp đồng/mã khách hàng này',
    '32022': 'Tổng số lần giao dịch vượt quá số lần quy định trong tháng với hợp đồng/mã khách hàng này',
    '32023': 'Tổng số lần giao dịch vượt quá hạn mức tối đa trong ngày',
    '32024': 'Quá số lần tra cứu giao dịch cho phép',
    '32025': 'Đã vượt quá giới hạn thử lại giao dịch',
    '32026': 'Số tiền giao dịch nhỏ hơn số tiền tối thiểu cho phép do ngân hàng quy định',
    '32027': 'Số tiền giao dịch lớn hơn số tiền tối đa cho phép do ngân hàng quy định',
    '32028': 'Số tiền giao dịch không đúng định dạng yêu cầu.',
    '32029': 'Số tiền giao dịch không hợp lệ',
    '32030': 'Số tiền giao dịch không khớp giữa hai đầu chuyển/nhận',
    '32031': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32032': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32033': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32035': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32036': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32037': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32038': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32039': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32040': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32041': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32042': 'Không hỗ trợ thực hiện giao dịch trên kênh giao dịch này',
    '32043': 'Loại giao dịch không được hỗ trợ thực hiện trên kênh giao dịch này',
    '32046': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32047': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32048': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32049': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32050': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32051': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32052': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32053': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32054': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32055': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32056': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32057': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32058': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32059': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32060': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32061': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32062': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32063': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32064': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32065': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32066': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32067': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32068': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32069': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32070': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32071': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32072': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32073': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32074': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32075': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32076': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32077': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32078': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32079': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '32080': 'Bạn không còn hạn mức chuyển khoản tới Ví trong tháng này. Vui lòng thực hiện lại phương thức này vào tháng tiếp theo',
    '33001': 'Số tiền hoàn trả vượt quá số tiền gốc',
    '33002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '33003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '33004': 'Quá thời gian cho phép thực hiện hoàn tiền',
    '33005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '33006': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '33007': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '33008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '33009': 'Giao dịch đã được hoàn tiền trước đó',
    '33010': 'Không thể hoàn tiền do giao dịch đang chờ quyết toán',
    '33011': 'Trạng thái giao dịch không hợp lệ để thực hiện hoàn tiền',
    '33012': 'Không thể hoàn tiền do giao dịch có khuyến mại, chọn hoàn khuyến mại để thực hiện giao dịch',
    '41001': 'Hóa đơn đã hết hạn',
    '41002': 'Hóa đơn đã được thanh toán',
    '41003': 'Hóa đơn đã bị hủy',
    '41004': 'Mã hóa đơn đã được xử lý',
    '41005': 'Thông tin hóa đơn không tồn tại',
    '41006': 'Trạng thái hóa đơn không hợp lệ',
    '41007': 'Có lỗi liên quan đến hóa đơn',
    '41008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41009': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41010': 'Khách hàng không còn nợ cước hóa đơn',
    '41011': 'Khách hàng có nhiều hơn một loại phí cần thanh toán. Chọn một loại phí để truy vấn thông tin thanh toán',
    '41012': 'Hoá đơn khách hàng đang bị khoá tại hệ thống của nhà cung cấp',
    '41013': 'Khách hàng đang nằm trong khu vực không hỗ trợ thanh toán',
    '41014': 'Không tìm thấy thông tin khách hàng thanh toán hoá đơn',
    '41015': 'Khách hàng không có hoá đơn',
    '41016': 'Khách hàng không tồn tại hoặc chưa phát sinh hoá đơn thanh toán',
    '41017': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41018': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41019': 'Nhà cung cấp không hỗ trợ tài khoản/số điện thoại này',
    '41020': 'Mã đặt chỗ hết thời gian hiệu lực hoặc đã được thanh toán',
    '41021': 'Cần thanh toán hóa đơn cũ trước',
    '41022': 'Cần thanh toán hóa đơn mới trước',
    '41023': 'Hoá đơn đã được gạch nợ',
    '41024': 'Số tiền giao dịch không khớp với số tiền trong hóa đơn',
    '41025': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41026': 'Kỳ thanh toán hoá đơn không hợp lệ',
    '41027': 'Mã hoá đơn không hợp lệ',
    '41051': 'Nhà cung cấp không hỗ trợ dịch vụ này',
    '41052': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41053': 'Dịch vụ nhà cung cấp đang tạm ngưng',
    '41054': 'Dịch vụ nhà cung cấp không tồn tại hoặc không được hỗ trợ',
    '41055': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41056': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41057': 'Dịch vụ nhà cung cấp chưa được hỗ trợ thanh toán',
    '41058': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41059': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41060': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41061': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41062': 'Khách hàng chưa đăng ký dịch vụ với nhà cung cấp',
    '41063': 'Gói dịch vụ smartbanking/bidv online của khách hàng không được thực hiện giao dịch online/liên kết ví',
    '41064': 'Khách hàng đang sử dụng BIDV Smart Banking gói phi tài chính. Khách hàng cần đăng ký BIDV Smart Banking gói tài chính để sử dụng dịch vụ.',
    '41065': 'Dịch vụ không hỗ trợ gói Fintech SmartBanking, để liên kết ví khách hàng cần ra quầy đổi gói để thực hiện giao dịch',
    '41066': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41067': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41068': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41069': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41070': 'Dịch vụ hiện đang được bảo trì',
    '41071': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41072': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '41073': '',
    '42001': 'Loại thẻ nạp không hợp lệ',
    '42002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '42003': 'Số lượng thẻ không đủ theo yêu cầu',
    '42004': 'Không hỗ trợ thanh toán mệnh giá thẻ này',
    '42005': 'Số lượng thẻ yêu cầu, giá trị giao dịch vượt quá giới hạn cho phép',
    '44001': 'Nguồn tiền không hợp lệ',
    '44002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '44003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '44004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '44005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '44006': 'Dịch vụ không hỗ trợ nguồn tiền này',
    '44007': 'Giao dịch không hỗ trợ nguồn tiền này',
    '44008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51101': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51102': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51103': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51104': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51105': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51106': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51107': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51108': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51109': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51110': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51111': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51112': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51113': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51114': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51115': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51201': 'Phiên đăng nhập hết hạn',
    '51202': 'Phiên làm việc hết hạn',
    '51203': 'Phiên xử lý KYC hết hạn, vui lòng xác thực lại',
    '51211': 'Hệ thống đang bảo trì',
    '51212': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51213': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51214': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51215': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51216': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51217': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51223': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51231': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51232': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51233': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51234': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51235': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51241': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51242': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51243': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51244': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51245': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51301': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51302': 'Thông tin OTP không chính xác',
    '51303': 'OTP đã hết hạn',
    '51304': 'Qúa thời gian chờ xác thực OTP',
    '51305': 'Bạn đã nhập sai mã xác thực OTP quá số lần cho phép. Vui lòng thử lại với OTP mới.',
    '51306': 'Bạn đã nhập sai mã xác thực OTP quá số lần cho phép. Vui lòng thử lại sau 60 phút.',
    '51307': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51308': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51309': 'Vượt quá số lần nhập sai PIN cho phép',
    '51310': 'Số PIN không chính xác',
    '51311': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51312': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51313': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51314': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51315': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51316': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51317': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51318': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51319': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51320': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51321': 'OTP đã được xác thực trước đó',
    '51322': 'Không thể xác thực OTP do chức năng gửi OTP đã bị khoá',
    '51323': '',
    '51324': 'Bạn đã yêu cầu gửi lại mã xác thực OTP quá 5 lần. Vui lòng thử lại sau 60 phút.',
    '51325': 'Giao dịch thất bại',
    '51401': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51402': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51403': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51404': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51405': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51406': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51407': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51408': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51409': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51410': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51411': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51412': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51413': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51414': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51415': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51416': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51417': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51421': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51422': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51423': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51424': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51425': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51426': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51431': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51432': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51441': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '51442': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52001': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52002': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52003': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52004': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52005': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52006': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52007': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52008': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52009': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
    '52010': '',
    '99999': 'Đã có lỗi xảy ra, vui lòng thử lại sau',
  };
}
